# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fe_TEKv4SuDivCSEFxFKwjvZs1WqEsWz
"""

# Functions

def sales_tax():
  x = int(input('Enter in the MSRP price of the object: '))
  y = float(input("Enter in the local, state, or federal tax: "))
  sales_tax = x * y
  tax = x - y
  x - tax
  return x
  
def aftertax():
  x = int(input('MSRP:'))
  y = float(input("Enter in the local, state, or federal tax: "))
  tax = x - y
  aftertax = x - tax
  return aftertax

sales_tax()
aftertax()

16000 * 0.09

16000 + 1440

